name: Deploy - Test proy
on: [push,workflow_call,workflow_dispatch]
env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install Node 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Intsall dependencies for node
        run: npm ci
      - name: LINT
        run : npm run lint
  test: 
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install Node 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Intsall dependencies for node
        run: npm ci
      - name: Run test package
        run : npm test
      - name: LINT
        run : npm run lint
  deploy: 
      runs-on: ubuntu-latest
      needs: [test]
      steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: install Node 
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Intsall dependencies for node
          run: npm ci
        - name: Build proy
          run : npm run build
        