name: Outputs information about
on: [push,workflow_call,workflow_dispatch]
env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name:  Outputs Github cotext information
        run: echo "${{ toJSON(github) }}"